### ISSUE TITLE
can we have multiple responses for different query params and same url?

### ISSUE THREAD

**Issue by Phalguna2125** [ClearC2/headlamp#37]
I have to modify the response based on query params but the response is giving back the same for different query param/different files. Is this possible?

**Comment by dadamssg** [comment]
@Phalguna2125 yes! you can use the `response` key(not `responses` with an "s"). 

```js
export default {
  path: '/people',
  methods: ['GET', 'POST', 'PUT'],
  response: (req, res) => {
    return // something based on the req object
  }
}
```

The only downside to this is you don't have have a mock response in the headlamp UI if you don't also fill out the `responses`.
